name: erlang
base: core18
version: '22.1'
summary: Erlang programming language and OTP in a snap 
description: |
  Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. Erlang's runtime system has built-in support for concurrency, distribution and fault tolerance.
grade: devel 
confinement: devmode 

apps:
  erlang:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/erl"   
  erl:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/erl"   
  erlc:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/erlc"
  dialyzer:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/dialyzer"
  typer:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/typer"  
  ct-run:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/ct_run"
  escript:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/escript"
  run-erl:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/run_erl"
  to-erl:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/to_erl"
  start:
    command:
      sh -c "/usr/otp_erlang/OTP/bin/start"
      
passthrough:
  layout:
    /usr/otp_erlang:
        bind: $SNAP/usr/otp_erlang
    /etc:
        bind: $SNAP/etc

parts:
  otp-erlang:
    plugin: autotools
    source: http://erlang.org/download/otp_src_22.1.tar.gz
    configflags:
      - --prefix=/usr/otp_erlang/OTP
      - CFLAGS=-g -O2
    override-build: |
      export ERL_TOP=/usr/otp_erlang/OTP
      export MAKEFLAGS=-j8
      snapcraftctl build
    build-packages:
      - build-essential
      - autoconf
      - libncurses-dev
      - libncursesw5-dev
      - libssh-dev
      - libwxgtk3.0-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - unixodbc-dev
      - openjdk-11-jdk
      - libatk-adaptor
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libatk-bridge2.0-0
      - libgail-common
    stage:
      - usr
      - etc
      - lib
      - sbin
      - var
    stage-packages:
      - libncurses-dev
      - libncursesw5-dev
      - libssh-dev
      - libwxgtk3.0-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - unixodbc-dev
      - libssh-4
      - libwxgtk3.0-0v5
      - libgl1-mesa-dri
      - libglu1-mesa
      - libpng16-16
      - unixodbc
      - openjdk-11-jdk
      - libatk-adaptor
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libatk-bridge2.0-0
      - libgail-common      
    prime:
      - usr
      - etc
      - lib
      - sbin
      - var
    override-prime: |
      export FONTCONFIG_PATH=/etc/fonts
      snapcraftctl prime
