#!/bin/bash -e
# based on:
# https://github.com/anonymouse64/device-grove-c/commit/03fca251f6fdfd48bb6e7fc6cbfdc07392039363

mkdir -p ${SNAP_DATA}/var/lib
cp -rf ${SNAP}/var/lib/ucf ${SNAP_DATA}/var/lib
